\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{atividade}[2020/04/09 Classe para resolução de exercícios]

\LoadClass[a4paper,11pt]{article}

\linespread{1.1}

\RequirePackage{geral}
\RequirePackage{analise}
\RequirePackage{teoremas}

\RequirePackage[shortlabels]{enumitem}

\RequirePackage[margin=2.5cm]{geometry}
\RequirePackage[makeroom]{cancel}
\RequirePackage{parskip}
\RequirePackage[shortlabels]{enumitem}
\RequirePackage{float}


\RequirePackage{tikz}
\usetikzlibrary{fit,shapes.geometric}
