\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{atividade}[2020/04/09 Classe para resolução de exercícios]

\LoadClass[a4paper,11pt]{article}

\RequirePackage{geral}
\RequirePackage{analise}
\RequirePackage{teoremas}

\RequirePackage[margin=3cm]{geometry}
\RequirePackage[makeroom]{cancel}
\RequirePackage{parskip}
\RequirePackage[shortlabels]{enumitem}


\RequirePackage{tikz}
\usetikzlibrary{fit,shapes.geometric}
